[package]
name = "datafusion-server"
version = "0.1.0"
description = "datafusion-server crate library command-line executor"
license = "MIT"
authors = ["Sasaki, Naoki <nsasaki@sal.co.jp>"]
keywords = ["datafusion-server"]
readme = "README.md"
edition = "2021"

[profile.release]
strip = true
lto = "fat"
codegen-units = 1

[features]
plugin = ["datafusion-server/plugin"]
flight = ["datafusion-server/flight"]
avro = ["datafusion-server/avro"]
webdav = ["datafusion-server/webdav"]
deltalake = ["datafusion-server/deltalake"]

[dependencies]
datafusion-server = { path = "../lib" }
clap = { version = "4.5.4", features = ["derive"] }
