# Configuration file of datafusion-server for production environment

[server]
port = 4000
flight_grpc_port = 50051 # only for enables `flight` feature
base_url = "/"
data_dir = "/var/datafusion-server/data"
plugin_dir = "/usr/local/datafusion-server/plugins"

[session]
default_keep_alive = 3600 # in seconds
upload_limit_size = 20 # 20MB

[log]
# trace, debug, info, warn, error
level = "info"
