[package]
name = "datafusion-server"
version = "0.8.4"
description = "Arrow and other large datasets web server library"
license-file = "LICENSE"
authors = ["Sasaki, Naoki <nsasaki@sal.co.jp>"]
keywords = ["http", "web", "arrow", "datafusion"]
readme = "README.md"
edition = "2021"
repository = "https://github.com/neural-runner/datafusion-server.git"

[profile.release]
strip = true
lto = "fat"
codegen-units = 1

[features]
# cargo build --release --features=plugin
plugin = ["pyo3", "datafusion/pyarrow"]

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
once_cell = "1.18"
config = "0.13"
regex = "1.9"
log = { version = "0.4", features = ["std"] }
simple_logger = { version = "4.2", features = ["timestamps"] }
clap = { version = "4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["preserve_order"] }
num-traits = "0.2"
chrono = { version = "0.4", default-features = false, features = ["std", "clock", "time"] }
jsonpath-rust = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["alloc"] }
futures = "0.3"
tokio = { version = "1.29", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
reqwest = { version = "0.11", features = ["default-tls", "cookies", "json", "stream"] }
tower = "0.4"
tower-http = { version = "0.4", features = ["cors"] }
axum = "0.6"
datafusion = { version = "31.0" }
pyo3 = { version = "0.19", optional = true }
