# datafusion-server - example configuration file

[server]
address = "0.0.0.0"
port = 4000
flist_address = "0.0.0.0"
flight_grpc_port = 50051
metrics_address = "127.0.0.1"
metrics_port = 9100
base_url = "/"
data_dir = "./data"
plugin_dir = "./plugins"

[session]
default_keep_alive = 3600 # in seconds
upload_limit_size = 20 # 20MB

[log]
# trace, debug, info, warn, error
level = "debug"

[[databases]]
type = "postgres"
namespace = "pg1"
user = "example"
password = "password"
host = "postgres-server.local"
port = 5432
database = "example"
ssl_mode = "prefer" # disable, allow, prefer (default), require, verify-ca, verify-full
max_connections = 30 # default 10
description = "PostgreSQL"

[[databases]]
type = "mysql"
namespace = "mysql1"
user = "root"
password = "password"
host = "mysql-server.local"
port = 3306
database = "example"
ssl_mode = "preferred" # disabled (default), preferred（default 5.7.3+), required, verify-ca, verify-identity
max_connections = 30 # default 10
description = "MySQL / MariaDB"

[[storages]]
type = "aws"
access_key_id = "AKIA"
secret_access_key = "SECRET"
region = "us-east-1"
bucket = "my-bucket"
description = "e.g. `s3://my-bucket/path/to/file.parquet` in data source location"

[[storages]]
type = "gcp"
service_account_key = "SERVICE_ACCOUNT_KEY"
bucket = "my-gcs-bucket"
description = "e.g. `gs://my-bucket/path/to/file.parquet` in data source location"

[[storages]]
type = "azure"
account_name = "AZURE_STORAGE_ACCOUNT_NAME"
access_key = "AZURE_STORAGE_ACCESS_KEY"
container = "my-container"
description = "e.g. `az://my-container/path/to/file.parquet` in data source location"

[[storages]]
type = "webdav"
url = "https://server.com"
user = "USER"
password = "PASSWORD"
description = "e.g. `https://server.com/dav/file.parquet` in data source location"
