name: Build and publish Docker images manually triggered

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Tag'
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and publish datafusion-server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: bin/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/datafusion-server:${{ github.event.inputs.version }}
            ghcr.io/${{ github.repository }}/datafusion-server:latest

      - name: Build and publish datafusion-server without plugin
        uses: docker/build-push-action@v2
        with:
          context: .
          file: bin/Dockerfile.without-plugin
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/datafusion-server-without-plugin:${{ github.event.inputs.version }}
            ghcr.io/${{ github.repository }}/datafusion-server-without-plugin:latest
