name: Build and publish Docker images triggered when pushed to main

on:
  push:
    branches:
      - main
    paths-ignore:
      - doc/**

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract current version from Cargo.toml
        id: cargo_version
        run: |
          CONTAINER_VER=$(grep '^version' ./Cargo.toml | head -1 | awk -F '"' '{print $2}')
          echo "CONTAINER_VER=$CONTAINER_VER" >> $GITHUB_ENV

      - name: Build and publish datafusion-server
        uses: docker/build-push-action@v5
        with:
          context: .
          file: bin/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/datafusion-server:${{ env.CONTAINER_VER }}
            ghcr.io/${{ github.repository }}/datafusion-server:latest

      - name: Build and publish datafusion-server without plugin
        uses: docker/build-push-action@v5
        with:
          context: .
          file: bin/Dockerfile.without-plugin
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/datafusion-server-without-plugin:${{ env.CONTAINER_VER }}
            ghcr.io/${{ github.repository }}/datafusion-server-without-plugin:latest
